from typing import Any, Optional

class VMServer:
    def start(self) -> None: ...
    def close(self) -> None: ...

class NodeVMModule:
    ...
    def call_member(self, member: str, *args: Any) -> Any: ...

class NodeVM:
    def __init__(self, server: Optional[VMServer] = None): ...
    def create(self) -> None: ...
    def destroy(self) -> None: ...
    def run(self, code: str) -> NodeVMModule: ...
